### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by iemeli** [JoakimJoensuu/BanknoteTracker#1]
Projekti ladattu 8.4. 21:45.

Kävin ensin testaamassa sovellusta Herokussa. Hieno sovellus, tässä vaiheessa jo paljon toiminnallisuuksia ja kivan näköinen layoutti kun kaikki sivun tavara on siinä keskellä. Mahtava pointti se, että tietokanta ottaa tunnukset selkokielisinä ettei joku mene laittamaan muiden sivujen tunnuksiaan sovellukseen.

Käyttäjätarinoita tarkastellen muutama ominaisuus ei toimi
-setelin poistaminen tuotti internal server errorin tietyssä tapauksessa. Näyttää siltä, että jos havaitun setelin yrittää poistaa, tulee errori. Tässä lienee jokin viitehässäkkä, voisikohan korjaantua sillä että poistaa ensin kaikki viitteet seteliin, ja sitten vasta setelin?
-tietyn setelin päivittäminen ei toimi

Hieno työ kokonaisuudessaan, itsellä ollut samoja ongelmia viitteiden poistamisessa. Tsemppiä tsohailuun!

**Comment by JoakimJoensuu** [comment]
Kiitos vinkeistä ja neuvoista!

![alt text](https://i.kym-cdn.com/entries/icons/original/000/014/711/neckbeard.jpg "Kiitän")
