### ISSUE TITLE
2. Koodikatselmointi

### ISSUE THREAD

**Issue by uberballo** [JoakimJoensuu/BanknoteTracker#2]
Ihan aluksi Readme on tosi selkeä ja opastaa erittäin hyvin miten ladata, asentaa sekä käyttää itse sovellusta. Ei tullut ainnuttakaan ongelmaa vastaan asennuksen ohella.

Sovellus toimi niinkuin piti, ei tullut virheitä vastaan, validointi toimi, oli admin sekä normaali käyttäjä jne. Eli kaikki kunnossa. Ainoat kohdat mitä parantaisi olisi muutamat ulkonäkö seikat. Esimerkiksi sivua "Joukkueet" on tosi hankala lukea. esim. siihen voisi lisätä hieman padding. Muuta valitettavaa ei ole.

Sovellus suorittaa kaiken mitä tähän saakka pitäisi suorittaa. Hyvää työtä!

ps. Jottai saisi vähän helppolukuisempaa esim. bootsrapissa on hyviä table esimerkkejä :)

**Comment by JoakimJoensuu** [comment]
Kiitti bro
